# Generated by Django 2.2 on 2020-05-13 15:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operation', '0002_auto_20200424_2019'),
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('add_times', models.DateTimeField(default=datetime.datetime.now, verbose_name='添加时间')),
                ('image', models.ImageField(upload_to='banner/%Y/%m', verbose_name='头像')),
                ('title', models.CharField(max_length=100, verbose_name='标题')),
                ('url', models.URLField(max_length=100, verbose_name='访问地址')),
                ('index', models.IntegerField(default=0, verbose_name='顺序')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
