# Generated by Django 2.2 on 2020-05-17 18:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('operation', '0003_banner'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='banner',
            options={'verbose_name': '轮播图', 'verbose_name_plural': '轮播图'},
        ),
    ]
