# Generated by Django 2.2 on 2020-05-07 11:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0006_course_notice'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='notice',
        ),
    ]
