# Generated by Django 2.2 on 2020-04-30 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='city',
            options={'verbose_name': '城市', 'verbose_name_plural': '城市'},
        ),
        migrations.AlterModelOptions(
            name='teacher',
            options={'verbose_name': '讲师', 'verbose_name_plural': '讲师'},
        ),
        migrations.AddField(
            model_name='courseorg',
            name='is_gold',
            field=models.BooleanField(blank=True, null=True, verbose_name='是否金牌'),
        ),
        migrations.AddField(
            model_name='courseorg',
            name='is_identification',
            field=models.BooleanField(blank=True, null=True, verbose_name='是否认证'),
        ),
        migrations.AlterField(
            model_name='city',
            name='name',
            field=models.CharField(max_length=20, verbose_name='城市名'),
        ),
    ]
