# Generated by Django 2.2 on 2020-04-30 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0002_auto_20200430_1600'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courseorg',
            name='is_gold',
            field=models.BooleanField(default=False, verbose_name='是否金牌'),
        ),
        migrations.AlterField(
            model_name='courseorg',
            name='is_identification',
            field=models.BooleanField(default=False, verbose_name='是否认证'),
        ),
    ]
